[[constraint]]
  name = "github.com/kisielk/gotool"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "pkg.re/essentialkaos/ek.v11"
  version = "11.2.1"

[prune]
  go-tests = true
  unused-packages = true
