name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 18 * * 0'

jobs:
  Ubuntu:
    name: Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.14.x', '1.15.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Setup PATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "GOBIN=${{ github.workspace }}/bin" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/essentialkaos/aligo

      - name: Install deps
        run: |
          mkdir -p $GOBIN
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Download dependencies
        run: make deps
        working-directory: src/github.com/essentialkaos/aligo

      - name: Run tests
        run: make all
        working-directory: src/github.com/essentialkaos/aligo
